version: '3.9'
services:
  build-frontend:
    image: node:16
    volumes:
      - .:/wol-web
    entrypoint: sh -c
    command:
      - |
        cd /wol-web/frontend
        rm -rf dist node_modules
        npm ci
        npm run build
  dev-frontend:
    image: node:16
    volumes:
      - ./frontend:/frontend
    entrypoint: sh -c
    command:
      - |
        cd /frontend
        rm -rf dist node_modules
        npm ci
        npm run serve
    network_mode: 'host'
  build-backend:
    image: golang:1.17.6-alpine3.15
    volumes:
      - ./backend:/backend
    entrypoint: sh -c
    command:
      - |
        cd /backend
        apk add build-base
        go build -o server .
  dev-backend:
    image: golang:1.17.6-alpine3.15
    volumes:
      - .:/wol
    entrypoint: sh -c "apk add build-base && go get -u github.com/cosmtrek/air && export PATH=/usr/local/go/bin:/go/bin:$PATH && cd /wol/backend && air"
    network_mode: 'host'
