name: Test If Compile
on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [master]
    paths:
      - 'frontend/**'
jobs:
  test-vue-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build frontend
        run: make build-frontend
  test-backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build frontend
        run: make build-backend
